service: ha-on-echo-show
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs22.x

# plugins:
#   - serverless-esbuild

# package:
#   patterns:
#     - 'documents/**'

# custom:
#   esbuild:
#     platform: 'node'
#     format: 'esm'
#     outputFileExtension: .mjs
#     exclude:
#       - '@aws-sdk/*'

functions:
  ha-assistant-skill:
    handler: index.handler
    environment:
      HA_ENDPOINT: ${ssm:/ha-assistant-skill/ha-endpoint}
      CAMERA_ENDPOINT: ${ssm:/ha-assistant-skill/camera-endpoint}
    events:
      - alexaSkill: ${ssm:/ha-assistant-skill/id}
